# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AttributesJoinByLine
                                 A QGIS plugin
 Plugin to create polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-16
        copyright            : (C) 2019 by Adrian Bocianowski
                             : The plug-in created thanks to the financial support of <a href="http://geofabryka.pl/">Geofabryka Sp. z o.o.</a>
        email                : adrian@bocianowski.com.pl
        git                  : tracker=https://github.com/abocianowski/AttributesJoinByLine/issues
                             : repository=https://github.com/abocianowski/AttributesJoinByLine
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    from .AttributesJoinByLine import AttributesJoinByLine
    return AttributesJoinByLine(iface)
